In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
%matplotlib inline

In [2]:
!wget -O FuelConsumption.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/FuelConsumptionCo2.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
df = pd.read_csv("FuelConsumption.csv", encoding='ISO-8859-1')

In [5]:
df.head()

,MODEL,MAKE,MODEL.1,VEHICLE CLASS,ENGINE SIZE,CYLINDERS,TRANSMISSION,FUEL,FUEL CONSUMPTION*,Unnamed: 9,Unnamed: 10,Unnamed: 11,CO2 EMISSIONS
0,YEAR,NaN,# = high output engine,NaN,(L),NaN,NaN,TYPE,CITY (L/100 km),HWY (L/100 km),COMB (L/100 km),COMB (mpg),(g/km)
1,2014,ACURA,ILX,COMPACT,2,4.0,AS5,Z,9.9,6.7,8.5,33,196
2,2014,ACURA,ILX,COMPACT,2.4,4.0,M6,Z,11.2,7.7,9.6,29,221
3,2014,ACURA,ILX HYBRID,COMPACT,1.5,4.0,AV7,Z,6,5.8,5.9,48,136
4,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6.0,AS6,Z,12.7,9.1,11.1,25,255

In [6]:
df.describe()

         CYLINDERS
count  1072.000000
mean      5.786381
std       1.797415
min       3.000000
25%       4.000000
50%       6.000000
75%       8.000000
max      12.000000